<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| ShopKart customer mobile API catalog for the Postman-style explorer.
| Endpoints below were verified with live curl against /shopkart-api/* (Jul 2026).
*/

$config['guide'] = [
    'base_path' => 'shopkart-api',
    'auth' => 'Send Authorization: Bearer <JWT> after login/register/otp-verify. Guest cart uses X-Session-ID.',
    'content_type' => 'application/json',
    'success_shape' => ['success' => true, 'message' => 'Success', 'data' => new stdClass()],
    'error_shape' => ['success' => false, 'message' => 'Error message', 'data' => []],
    'tips' => [
        '1. Call Register or Login first — the explorer auto-saves the JWT into the Token box.',
        '2. For guest cart, set any stable X-Session-ID (e.g. mobile-device-uuid).',
        '3. Use a product_id that has stock > 0 before Cart Add / Checkout.',
        '4. Malaysian phones: 0123456789 or 60123456789 (normalized to 60…).',
        '5. Payment verify needs a real Razorpay payload — samples show expected shape.',
        '6. Affiliate portal APIs use affiliate JWT from Affiliate Login (not customer JWT). Approve the affiliate in Admin before login succeeds.',
        '7. OTP signup: do NOT invent names like SER001 / User 1234. New users get empty name + email null; collect real name (required) and optional company/email on checkout or profile.',
        '8. Checkout address.full_name is saved onto the user account. Optional email must be unique (or omit/null). Optional address.company_name for invoices.',
        '9. Checkout must send order_source: "app" (or header X-Order-Source: app) so Admin Orders can show Web vs App.',
    ],
];

$config['groups'] = [
    'auth'       => '1. Authentication',
    'catalog'    => '2. Catalog & Home',
    'cart'       => '3. Cart',
    'wishlist'   => '4. Wishlist',
    'user'       => '5. User Account',
    'promo'      => '7. Promo',
    'orders'     => '8. Orders & Checkout',
    'shipping'   => '9. Shipping',
    'payment'    => '10. Payment',
    'notifications' => '10b. Push Notifications',
    'reviews'    => '11. Reviews',
    'content'    => '12. Content & SEO',
    'affiliate'  => '13. Affiliate (Enquiry + Portal)',
    'contact'    => '14. Contact',
    'misc'       => '15. Newsletter & Misc',
];

$config['catalog'] = [

    /* ========== AUTH ========== */
    [
        'id' => 'auth-register',
        'group' => 'auth',
        'name' => 'Register',
        'method' => 'POST',
        'path' => 'register',
        'auth' => false,
        'verified' => true,
        'how' => 'Create a customer account. Phone required (MY format). Rejects duplicate email/phone. Optional nested address. Returns JWT + user. Status 201.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'name' => 'API Docs User',
            'email' => 'customer@example.com',
            'password' => 'Test@1234',
            'phone' => '0123456789',
            'address' => [
                'line1' => '12 Jalan Test',
                'line2' => '',
                'city' => 'Kuala Lumpur',
                'state' => 'Wilayah Persekutuan',
                'pincode' => '50000',
            ],
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Registration successful.',
            'data' => [
                'token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...',
                'user' => [
                    'id' => '6',
                    'name' => 'API Docs User',
                    'email' => 'customer@example.com',
                    'phone' => '60123456789',
                    'status' => '1',
                ],
            ],
        ],
    ],
    [
        'id' => 'auth-check-availability',
        'group' => 'auth',
        'name' => 'Check Email/Phone Availability',
        'method' => 'POST',
        'path' => 'check-availability',
        'auth' => false,
        'verified' => true,
        'how' => 'Pre-register check. Send email and/or phone. Returns available true/false per field. HTTP 409 when taken.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['email' => 'customer@example.com', 'phone' => '0123456789'],
        'sample_response' => [
            'success' => true,
            'message' => 'Available.',
            'data' => [
                'email' => ['available' => true, 'message' => 'Email is available.'],
                'phone' => ['available' => true, 'message' => 'Phone number is available.'],
            ],
        ],
    ],
    [
        'id' => 'auth-login',
        'group' => 'auth',
        'name' => 'Login',
        'method' => 'POST',
        'path' => 'login',
        'auth' => false,
        'verified' => true,
        'how' => 'Email + password login. Returns JWT. Use token for all protected APIs.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['email' => 'customer@example.com', 'password' => 'Test@1234'],
        'sample_response' => [
            'success' => true,
            'message' => 'Login successful.',
            'data' => [
                'token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...',
                'user' => ['id' => '6', 'name' => 'API Docs User', 'email' => 'customer@example.com'],
            ],
        ],
    ],
    [
        'id' => 'auth-otp-request',
        'group' => 'auth',
        'name' => 'OTP Request',
        'method' => 'POST',
        'path' => 'otp-request',
        'auth' => false,
        'verified' => true,
        'how' => 'Send SMS OTP to Malaysian mobile. Test phones / local dev may return test_otp in response.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['phone' => '0123456789'],
        'sample_response' => [
            'success' => true,
            'message' => 'OTP ready for +60123456789 (local dev mode). Use OTP 1234.',
            'data' => [
                'phone' => '60123456789',
                'test_mode' => true,
                'test_otp' => '1234',
            ],
        ],
    ],
    [
        'id' => 'auth-otp-verify',
        'group' => 'auth',
        'name' => 'OTP Verify',
        'method' => 'POST',
        'path' => 'otp-verify',
        'auth' => false,
        'verified' => true,
        'how' => 'Verify OTP. Auto-registers new phone users with empty name and email=null (never SER001 / User ####). Optional body name upgrades placeholder/empty names. Returns JWT, user, is_new, profile_complete (true only when real name set — email not required), has_address. If profile_complete is false, show delivery name (+ optional company/email) before or at checkout.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['phone' => '0123456789', 'otp' => '1234', 'name' => ''],
        'sample_response' => [
            'success' => true,
            'message' => 'Account created. Login successful.',
            'data' => [
                'token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...',
                'user' => ['id' => '7', 'name' => '', 'email' => null, 'phone' => '60123456789'],
                'is_new' => true,
                'profile_complete' => false,
                'has_address' => false,
            ],
        ],
    ],
    [
        'id' => 'auth-forgot',
        'group' => 'auth',
        'name' => 'Forgot Password',
        'method' => 'POST',
        'path' => 'forgot-password',
        'auth' => false,
        'verified' => true,
        'how' => 'Email a 6-digit reset code. OTP-only (@shopkart.app) accounts cannot use this. Dev may return dev_code.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['email' => 'customer@example.com'],
        'sample_response' => [
            'success' => true,
            'message' => 'SMTP not configured. Use verification code: 358632',
            'data' => ['dev_code' => '358632'],
        ],
    ],
    [
        'id' => 'auth-forgot-verify',
        'group' => 'auth',
        'name' => 'Verify Reset Code',
        'method' => 'POST',
        'path' => 'forgot-password/verify',
        'auth' => false,
        'verified' => true,
        'how' => 'Validate 6-digit email code. Returns reset_token for the next step.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['email' => 'customer@example.com', 'code' => '358632'],
        'sample_response' => [
            'success' => true,
            'message' => 'Email verified. You can now set a new password.',
            'data' => ['reset_token' => 'abc123reset...'],
        ],
    ],
    [
        'id' => 'auth-reset',
        'group' => 'auth',
        'name' => 'Reset Password',
        'method' => 'POST',
        'path' => 'reset-password',
        'auth' => false,
        'verified' => true,
        'how' => 'Set new password using reset_token from verify step. Min 6 chars; password_confirmation must match.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'email' => 'customer@example.com',
            'reset_token' => 'abc123reset...',
            'password' => 'NewPass@123',
            'password_confirmation' => 'NewPass@123',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Password updated successfully. You can now sign in.',
            'data' => [],
        ],
    ],
    [
        'id' => 'auth-logout',
        'group' => 'auth',
        'name' => 'Logout',
        'method' => 'POST',
        'path' => 'logout',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Blacklists the current Bearer token until it expires. Mobile should clear local token after success.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => new stdClass(),
        'sample_response' => [
            'success' => true,
            'message' => 'Logged out successfully.',
            'data' => [],
        ],
    ],
    [
        'id' => 'auth-delete-account',
        'group' => 'auth',
        'name' => 'Delete Account',
        'method' => 'POST',
        'path' => 'user/delete-account',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Soft-deletes account (users.deleted_at) and blacklists token. Email/password accounts must send password. OTP (@shopkart.app) accounts send confirm=true.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['password' => 'Test@1234'],
        'sample_response' => [
            'success' => true,
            'message' => 'Your account has been deleted.',
            'data' => [],
        ],
    ],

    /* ========== CATALOG ========== */
    [
        'id' => 'catalog-products',
        'group' => 'catalog',
        'name' => 'List Products',
        'method' => 'GET',
        'path' => 'products',
        'auth' => false,
        'verified' => true,
        'how' => 'Paginated product list. Filters: category_id, category_slug, subcategory_id, brand_id, q, featured, nav_featured, special_product, min_price, max_price, sort, fabric, saree_type, occasion. sort examples: price_asc, price_desc, newest.',
        'query' => ['limit' => '1', 'page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'products' => [['id' => '31', 'name' => 'South Indian Bridal Silk - Gold', 'price' => 0, 'stock' => 0]],
                'total' => 40,
                'page' => 1,
                'limit' => 1,
                'total_pages' => 40,
            ],
        ],
    ],
    [
        'id' => 'catalog-recommended',
        'group' => 'catalog',
        'name' => 'Recommended Products',
        'method' => 'GET',
        'path' => 'products/recommended',
        'auth' => false,
        'verified' => true,
        'how' => 'Home recommended list. Uses special_product=1; falls back to featured=1 if empty. Supports limit & page.',
        'query' => ['limit' => '10', 'page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'products' => [['id' => '31', 'name' => 'South Indian Bridal Silk - Gold', 'special_product' => '1']],
                'total' => 5,
                'page' => 1,
                'limit' => 10,
                'total_pages' => 1,
            ],
        ],
    ],
    [
        'id' => 'catalog-new-arrivals',
        'group' => 'catalog',
        'name' => 'New Arrivals',
        'method' => 'GET',
        'path' => 'products/new-arrivals',
        'auth' => false,
        'verified' => true,
        'how' => 'Newest active products (sort=newest / created_at DESC). Supports limit & page.',
        'query' => ['limit' => '10', 'page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'products' => [['id' => '40', 'name' => 'New Silk Collection', 'created_at' => '2026-07-28 10:00:00']],
                'total' => 12,
                'page' => 1,
                'limit' => 10,
                'total_pages' => 2,
            ],
        ],
    ],
    [
        'id' => 'catalog-top-selling',
        'group' => 'catalog',
        'name' => 'Top Selling Products',
        'method' => 'GET',
        'path' => 'products/top-selling',
        'auth' => false,
        'verified' => true,
        'how' => 'Best sellers by total_sold DESC. Supports limit & page.',
        'query' => ['limit' => '10', 'page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'products' => [['id' => '31', 'name' => 'South Indian Bridal Silk - Gold', 'total_sold' => 120]],
                'total' => 8,
                'page' => 1,
                'limit' => 10,
                'total_pages' => 1,
            ],
        ],
    ],
    [
        'id' => 'catalog-product',
        'group' => 'catalog',
        'name' => 'Product Detail',
        'method' => 'GET',
        'path' => 'product/31',
        'auth' => false,
        'verified' => true,
        'how' => 'Single product by numeric id or slug. Includes variants, images, related, seo.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'id' => '31',
                'name' => 'South Indian Bridal Silk - Gold',
                'slug' => 'south-indian-bridal-silk-gold',
                'variants' => [['id' => '1', 'label' => '1 Box', 'stock' => '0', 'price' => '0.00']],
                'related' => [],
                'seo' => ['meta_title' => 'South Indian Bridal Silk - Gold | 2DEAL'],
            ],
        ],
    ],
    [
        'id' => 'catalog-search',
        'group' => 'catalog',
        'name' => 'Search Products',
        'method' => 'GET',
        'path' => 'search',
        'auth' => false,
        'verified' => true,
        'how' => 'Quick search. Query param q is required. Returns array of matching products (max 20).',
        'query' => ['q' => 'silk'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [['id' => '31', 'name' => 'South Indian Bridal Silk - Gold']],
        ],
    ],
    [
        'id' => 'catalog-categories',
        'group' => 'catalog',
        'name' => 'Categories',
        'method' => 'GET',
        'path' => 'categories',
        'auth' => false,
        'verified' => true,
        'how' => 'Full category tree for browse / filters.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [['id' => '1', 'name' => 'Silk Sarees', 'slug' => 'silk-sarees']],
        ],
    ],
    [
        'id' => 'catalog-nav',
        'group' => 'catalog',
        'name' => 'Nav Mega Menu',
        'method' => 'GET',
        'path' => 'nav-menu',
        'auth' => false,
        'verified' => true,
        'how' => 'Header mega-menu: categories + featured products for the app home/nav.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => ['categories' => [], 'featured' => []],
        ],
    ],
    [
        'id' => 'catalog-banners',
        'group' => 'catalog',
        'name' => 'Home Banners',
        'method' => 'GET',
        'path' => 'banners',
        'auth' => false,
        'verified' => true,
        'how' => 'Hero / home carousel banners with CTA links.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [['id' => '1', 'title' => 'Find Your Signature Style', 'cta_text' => 'Shop Styles']],
        ],
    ],
    [
        'id' => 'catalog-offer',
        'group' => 'catalog',
        'name' => 'Offer Banner',
        'method' => 'GET',
        'path' => 'offer-banner',
        'auth' => false,
        'verified' => true,
        'how' => 'Single offer strip banner. data may be null if none configured.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => ['success' => true, 'message' => 'Success', 'data' => null],
    ],
    [
        'id' => 'catalog-collection',
        'group' => 'catalog',
        'name' => 'Collection Banners',
        'method' => 'GET',
        'path' => 'collection-banners',
        'auth' => false,
        'verified' => true,
        'how' => 'Collection / seasonal banners for home sections.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [['id' => '11', 'title' => 'Fresh Seasonal Designs', 'subtitle' => 'New Arrivals']],
        ],
    ],
    [
        'id' => 'catalog-units',
        'group' => 'catalog',
        'name' => 'Variant Units',
        'method' => 'GET',
        'path' => 'variant-units',
        'auth' => false,
        'verified' => true,
        'how' => 'Unit master list (kg, box, piece…) used by product variants.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [['id' => '1', 'name' => 'Kilogram', 'slug' => 'kilogram', 'symbol' => 'kg']],
        ],
    ],

    /* ========== CART ========== */
    [
        'id' => 'cart-products',
        'group' => 'cart',
        'name' => 'My Cart Products',
        'method' => 'GET',
        'path' => 'cart/products',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Mobile alias for GET cart. Returns items (full product details) + summary only — no auto-suggestions. Use JWT for logged-in user cart, or X-Session-ID for guest. Keep the same session id across guest adds, then call POST cart/merge after login so web + app stay in sync.',
        'query' => [],
        'headers' => ['X-Session-ID' => 'mobile-guest-session-1'],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'items' => [],
                'summary' => ['subtotal' => 0, 'shipping' => 0, 'tax' => 0, 'total' => 0, 'item_count' => 0],
            ],
        ],
    ],
    [
        'id' => 'cart-merge',
        'group' => 'cart',
        'name' => 'Merge Guest Cart',
        'method' => 'POST',
        'path' => 'cart/merge',
        'auth' => 'jwt',
        'verified' => true,
        'how' => 'JWT required. Moves guest cart lines (X-Session-ID or body.session_id) into the logged-in user cart, merging quantities for the same product+variant. Call once right after login on mobile/web.',
        'query' => [],
        'headers' => ['Authorization' => 'Bearer <token>', 'X-Session-ID' => 'mobile-guest-session-1'],
        'body' => ['session_id' => 'mobile-guest-session-1'],
        'sample_response' => [
            'success' => true,
            'message' => 'Guest cart merged.',
            'data' => ['merged' => 2, 'items' => [], 'summary' => ['item_count' => 2]],
        ],
    ],
    [
        'id' => 'cart-get',
        'group' => 'cart',
        'name' => 'Get Cart',
        'method' => 'GET',
        'path' => 'cart',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Logged-in: uses JWT user cart. Guest: send X-Session-ID. Each pack variant is a separate line (product_id + variant_id). Returns items + summary with free_delivery eligibility. When cart is below free-delivery threshold, also returns suggestions.products (same pack variant in same category, full product detail). Query: include_suggestions=0 to skip, suggestions_limit=12. After login call POST cart/merge then GET cart/products to sync with mobile.',
        'query' => ['include_suggestions' => '1', 'suggestions_limit' => '12'],
        'headers' => ['X-Session-ID' => 'mobile-guest-session-1'],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'items' => [
                    [
                        'cart_id' => 12,
                        'product_id' => 30,
                        'variant_id' => 5,
                        'variant_label' => '500 g',
                        'unit_label' => '500 g',
                        'unit_name' => 'Gram',
                        'unit_symbol' => 'g',
                        'unit_value' => 500,
                        'product_name' => 'Sample Product',
                        'name' => 'Sample Product (500 g)',
                        'category_id' => 3,
                        'category_name' => 'Spices',
                        'sku' => 'SP-500G',
                        'thumbnail' => 'assets/uploads/products/sample.jpg',
                        'quantity' => 1,
                        'price' => 100,
                        'effective_price' => 100,
                        'subtotal' => 100,
                        'created_at' => '2026-07-29 09:15:00',
                        'added_at' => '2026-07-29 09:15:00',
                    ],
                ],
                'summary' => [
                    'subtotal' => 100,
                    'shipping' => 50,
                    'tax' => 0,
                    'discount' => 0,
                    'total' => 150,
                    'item_count' => 1,
                    'free_delivery' => [
                        'eligible' => false,
                        'threshold' => 999,
                        'shipping_charge' => 50,
                        'amount_remaining' => 899,
                        'currency' => 'RM',
                        'message' => 'Add RM899.00 more for free delivery.',
                    ],
                ],
                'suggestions' => [
                    'title' => 'More 500 g packs in this category',
                    'reason' => 'same_variant_same_category',
                    'based_on' => [
                        [
                            'product_id' => 30,
                            'product_name' => 'Sample Product',
                            'category_id' => 3,
                            'variant_label' => '500 g',
                            'unit_id' => 2,
                            'unit_value' => 500,
                        ],
                    ],
                    'products' => [
                        [
                            'id' => 31,
                            'name' => 'Related Pack Product',
                            'slug' => 'related-pack-product',
                            'category_id' => 3,
                            'category_name' => 'Spices',
                            'price' => 120,
                            'sale_price' => null,
                            'effective_price' => 120,
                            'unit_label' => '500 g',
                            'default_variant_id' => 8,
                            'matched_variant_id' => 8,
                            'suggestion_reason' => 'same_variant',
                            'images' => [],
                            'videos' => [],
                            'variants' => [],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'id' => 'cart-add',
        'group' => 'cart',
        'name' => 'Add to Cart',
        'method' => 'POST',
        'path' => 'cart/add',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Add product with optional variant_id (pack size). Same product + different variants become separate cart lines. Quantity defaults to 1. Fails if stock insufficient. Response includes variant fields when logged in.',
        'query' => [],
        'headers' => [
            'Content-Type' => 'application/json',
            'X-Session-ID' => 'mobile-guest-session-1',
        ],
        'body' => ['product_id' => 30, 'variant_id' => 5, 'quantity' => 1],
        'sample_response' => [
            'success' => true,
            'message' => 'Added to cart.',
            'data' => [
                'items' => [[
                    'product_id' => 30,
                    'variant_id' => 5,
                    'variant_label' => '500 g',
                    'name' => 'Sample Product (500 g)',
                    'category_name' => 'Spices',
                    'quantity' => 1,
                    'subtotal' => 100,
                    'created_at' => '2026-07-29 09:15:00',
                ]],
                'summary' => [
                    'item_count' => 1,
                    'total' => 150,
                ],
            ],
        ],
    ],
    [
        'id' => 'cart-update',
        'group' => 'cart',
        'name' => 'Update Cart Qty',
        'method' => 'POST',
        'path' => 'cart/update',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Set quantity for one product/variant line. Always send variant_id when the product has pack variants. quantity <= 0 removes the line.',
        'query' => [],
        'headers' => [
            'Content-Type' => 'application/json',
            'X-Session-ID' => 'mobile-guest-session-1',
        ],
        'body' => ['product_id' => 30, 'variant_id' => 5, 'quantity' => 2],
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => ['items' => [], 'summary' => ['item_count' => 0]],
        ],
    ],
    [
        'id' => 'cart-remove',
        'group' => 'cart',
        'name' => 'Remove Cart Item',
        'method' => 'POST',
        'path' => 'cart/remove',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Remove one line by product_id + variant_id (required when packs exist so other variants stay in cart).',
        'query' => [],
        'headers' => [
            'Content-Type' => 'application/json',
            'X-Session-ID' => 'mobile-guest-session-1',
        ],
        'body' => ['product_id' => 30, 'variant_id' => 5],
        'sample_response' => [
            'success' => true,
            'message' => 'Removed from cart.',
            'data' => [
                'items' => [],
                'summary' => [
                    'subtotal' => 0,
                    'shipping' => 0,
                    'tax' => 0,
                    'total' => 0,
                    'item_count' => 0,
                ],
            ],
        ],
    ],
    [
        'id' => 'cart-clear',
        'group' => 'cart',
        'name' => 'Clear Cart',
        'method' => 'POST',
        'path' => 'cart/clear',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Delete all cart lines for the current user or guest session.',
        'query' => [],
        'headers' => [
            'Content-Type' => 'application/json',
            'X-Session-ID' => 'mobile-guest-session-1',
        ],
        'body' => new stdClass(),
        'sample_response' => ['success' => true, 'message' => 'Cart cleared.', 'data' => []],
    ],
    [
        'id' => 'cart-suggestions',
        'group' => 'cart',
        'name' => 'Cart Suggestions',
        'method' => 'GET',
        'path' => 'cart/suggestions',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Same-category products matching cart pack variant (unit_id+unit_value or label). Full product detail (images, videos, variants, prices). Matching pack is preferred as default_variant. Also returns free_delivery eligibility for upsell messaging. Empty cart → empty products.',
        'query' => ['limit' => '12'],
        'headers' => ['X-Session-ID' => 'mobile-guest-session-1'],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'title' => 'More 500 g packs in this category',
                'reason' => 'same_variant_same_category',
                'free_delivery' => [
                    'eligible' => false,
                    'threshold' => 999,
                    'amount_remaining' => 899,
                    'message' => 'Add RM899.00 more for free delivery.',
                ],
                'products' => [
                    [
                        'id' => 31,
                        'name' => 'Related Pack Product',
                        'slug' => 'related-pack-product',
                        'category_id' => 3,
                        'category_name' => 'Spices',
                        'description' => 'Full product description…',
                        'price' => 120,
                        'sale_price' => null,
                        'effective_price' => 120,
                        'unit_label' => '500 g',
                        'default_variant_id' => 8,
                        'matched_variant_id' => 8,
                        'suggestion_reason' => 'same_variant',
                        'images' => [['image' => 'assets/uploads/products/a.jpg']],
                        'videos' => [],
                        'variants' => [
                            ['id' => 8, 'label' => '500 g', 'price' => 120, 'stock' => 20, 'is_default' => 1],
                        ],
                    ],
                ],
                'based_on' => [
                    [
                        'product_id' => 30,
                        'product_name' => 'Sample Product',
                        'category_id' => 3,
                        'variant_label' => '500 g',
                        'unit_id' => 2,
                        'unit_value' => 500,
                    ],
                ],
            ],
        ],
    ],

    /* ========== WISHLIST ========== */
    [
        'id' => 'wishlist-get',
        'group' => 'wishlist',
        'name' => 'Get Wishlist',
        'method' => 'GET',
        'path' => 'wishlist',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Returns wishlisted products for the logged-in customer.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => ['success' => true, 'message' => 'Success', 'data' => []],
    ],
    [
        'id' => 'wishlist-toggle',
        'group' => 'wishlist',
        'name' => 'Toggle Wishlist',
        'method' => 'POST',
        'path' => 'wishlist/toggle',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Adds if missing, removes if present. Returns action: added|removed.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['product_id' => 31],
        'sample_response' => [
            'success' => true,
            'message' => 'Added to wishlist.',
            'data' => ['action' => 'added'],
        ],
    ],

    /* ========== USER ========== */
    [
        'id' => 'user-profile-get',
        'group' => 'user',
        'name' => 'Get Profile',
        'method' => 'GET',
        'path' => 'user/profile',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Returns customer profile (password fields stripped). email may be null. Includes profile_complete (true when name is a real name — not empty / User|SER|USR|CUST + digits).',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'id' => '6',
                'name' => 'API Docs User',
                'email' => null,
                'phone' => '60123456789',
                'status' => '1',
                'profile_complete' => true,
            ],
        ],
    ],
    [
        'id' => 'user-profile-put',
        'group' => 'user',
        'name' => 'Update Profile',
        'method' => 'PUT',
        'path' => 'user/profile',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Updatable: name, phone, email (optional), password. Send email as string to set (must be unique) or "" to clear placeholders to null. Do not invent SER001-style names.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['name' => 'Siti Aminah', 'phone' => '0123456789', 'email' => 'siti@example.com'],
        'sample_response' => [
            'success' => true,
            'message' => 'Profile updated.',
            'data' => ['id' => '6', 'name' => 'Siti Aminah', 'email' => 'siti@example.com', 'phone' => '60123456789'],
        ],
    ],
    [
        'id' => 'user-dashboard',
        'group' => 'user',
        'name' => 'User Dashboard',
        'method' => 'GET',
        'path' => 'user/dashboard',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Stats (orders, spent, addresses) + recent_orders with items.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'stats' => [
                    'total_orders' => 0,
                    'pending' => 0,
                    'delivered' => 0,
                    'total_spent' => 0,
                    'addresses' => 0,
                ],
                'recent_orders' => [],
            ],
        ],
    ],
    [
        'id' => 'user-change-password',
        'group' => 'user',
        'name' => 'Change Password',
        'method' => 'POST',
        'path' => 'user/change-password',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Needs current_password, new_password, confirm_password (min 6).',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'current_password' => 'Test@1234',
            'new_password' => 'Test@5678',
            'confirm_password' => 'Test@5678',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Password changed successfully.',
            'data' => [],
        ],
    ],
    [
        'id' => 'user-addresses',
        'group' => 'user',
        'name' => 'List Addresses',
        'method' => 'GET',
        'path' => 'user/addresses',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. All saved shipping/billing addresses.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => ['success' => true, 'message' => 'Success', 'data' => []],
    ],
    [
        'id' => 'user-address-save',
        'group' => 'user',
        'name' => 'Save Address',
        'method' => 'POST',
        'path' => 'user/addresses',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Required: full_name, phone, line1, city, state, pincode. Optional: id (update), label, line2, country, company_name, address_type shipping|billing, is_default.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'full_name' => 'Siti Aminah',
            'company_name' => 'Siti Trading Sdn Bhd',
            'phone' => '0123456789',
            'line1' => '12 Jalan Test',
            'line2' => 'Unit 3',
            'city' => 'Kuala Lumpur',
            'state' => 'Wilayah Persekutuan',
            'pincode' => '50000',
            'country' => 'Malaysia',
            'label' => 'Home',
            'address_type' => 'shipping',
            'is_default' => 1,
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Address saved.',
            'data' => ['id' => 1, 'addresses' => []],
        ],
    ],
    [
        'id' => 'user-address-delete',
        'group' => 'user',
        'name' => 'Delete Address',
        'method' => 'DELETE',
        'path' => 'user/addresses/1',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Replace :id in path with address id. Returns remaining addresses.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Address deleted.',
            'data' => ['addresses' => []],
        ],
    ],


    /* ========== PUSH NOTIFICATIONS ========== */
    [
        'id' => 'device-token-register',
        'group' => 'notifications',
        'name' => 'Register FCM Device Token',
        'method' => 'POST',
        'path' => 'user/device-token',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Call after Firebase Messaging getToken(). platform: android|ios|web.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['token' => 'fcm_device_token_here', 'platform' => 'android'],
        'sample_response' => [
            'success' => true,
            'message' => 'Device token registered.',
            'data' => ['token' => 'fcm_device_token_here', 'platform' => 'android'],
        ],
    ],
    [
        'id' => 'device-token-remove',
        'group' => 'notifications',
        'name' => 'Unregister FCM Device Token',
        'method' => 'POST',
        'path' => 'user/device-token/remove',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Call on logout. DELETE /user/device-token also works with same body.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['token' => 'fcm_device_token_here'],
        'sample_response' => [
            'success' => true,
            'message' => 'Device token removed.',
            'data' => [],
        ],
    ],
    [
        'id' => 'notifications-list',
        'group' => 'notifications',
        'name' => 'Notification Inbox',
        'method' => 'GET',
        'path' => 'notifications',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Recent sent campaigns with media_type none|image|video|both and absolute media URLs.',
        'query' => ['limit' => '20'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'notifications' => [
                    [
                        'id' => 1,
                        'title' => 'Flash sale',
                        'body' => 'Tonight only',
                        'media_type' => 'image',
                        'image_url' => 'https://example.com/banner.jpg',
                        'video_url' => null,
                        'click_url' => null,
                        'sent_at' => '2026-08-04 12:00:00',
                    ],
                ],
                'total' => 1,
            ],
        ],
    ],

    /* ========== PROMO ========== */
    [
        'id' => 'promo-apply',
        'group' => 'promo',
        'name' => 'Apply Coupon',
        'method' => 'POST',
        'path' => 'apply-coupon',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Validates promo or affiliate market code against order_amount. Returns discount + source.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['code' => 'SAVE10', 'order_amount' => 100],
        'sample_response' => [
            'success' => false,
            'message' => 'Invalid affiliate promo code.',
            'data' => [],
        ],
    ],

    /* ========== ORDERS ========== */
    [
        'id' => 'order-checkout',
        'group' => 'orders',
        'name' => 'Checkout',
        'method' => 'POST',
        'path' => 'checkout',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Cart must have items. payment_method: razorpay|cod. Do NOT call payment/create-order when payment.next_step=complete. Show data.message and clear local cart using data.cart_clear_lines (product_id list). Optional promo_code, billing_same, billing_address, notes. address.full_name required. payment.next_step: complete (COD) | create_payment_order (open Razorpay).',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json', 'X-Order-Source' => 'app'],
        'body' => [
            'payment_method' => 'razorpay',
            'promo_code' => '',
            'billing_same' => true,
            'note' => '',
            'order_source' => 'app',
            'email' => 'siti@example.com',
            'address' => [
                'full_name' => 'Siti Aminah',
                'company_name' => 'Siti Trading Sdn Bhd',
                'phone' => '0123456789',
                'line1' => '12 Jalan Test',
                'line2' => '',
                'city' => 'Kuala Lumpur',
                'state' => 'Wilayah Persekutuan',
                'pincode' => '50000',
                'country' => 'Malaysia',
            ],
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Order saved. Complete Razorpay payment to confirm.',
            'data' => [
                'order' => [
                    'id' => 101,
                    'order_number' => 'SK-20260728-001',
                    'total' => 230.50,
                    'payment_status' => 'paid',
                    'payment_method' => 'razorpay',
                    'status' => 'payment_attempt',
                ],
                'confirmed' => true,
                'cart_clear_lines' => [
                    ['product_id' => 12, 'variant_id' => 3],
                ],
                'payment' => [
                    'requires_gateway' => true,
                    'gateway_amount' => 230.50,
                    'next_step' => 'create_payment_order',
                ],
            ],
        ],
    ],
    [
        'id' => 'order-list',
        'group' => 'orders',
        'name' => 'My Orders',
        'method' => 'GET',
        'path' => 'orders',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Query page (10 per page). Each order includes items + tracking fields.',
        'query' => ['page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => ['success' => true, 'message' => 'Success', 'data' => []],
    ],
    [
        'id' => 'order-show',
        'group' => 'orders',
        'name' => 'Order Detail',
        'method' => 'GET',
        'path' => 'order/1',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Replace :id. Returns order belonging to current user only.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => ['id' => 1, 'order_number' => 'SK-...', 'items' => [], 'status' => 'pending'],
        ],
    ],
    [
        'id' => 'order-cancel',
        'group' => 'orders',
        'name' => 'Cancel Order',
        'method' => 'POST',
        'path' => 'order/1/cancel',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Cancel only when status allows (typically pending/confirmed before ship).',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => new stdClass(),
        'sample_response' => [
            'success' => true,
            'message' => 'Order cancelled.',
            'data' => ['order' => ['id' => 1, 'status' => 'cancelled']],
        ],
    ],
    [
        'id' => 'order-invoice',
        'group' => 'orders',
        'name' => 'Order Invoice Links',
        'method' => 'GET',
        'path' => 'order/1/invoice',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Replace :id with your order id (must belong to the logged-in user). Returns signed public download_url / view_url (no auth to open) plus api_download (Bearer PDF stream). Use download_url in email/WhatsApp; use api_download from the mobile app with JWT.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'order_id' => 1,
                'order_number' => 'SK903246A0',
                'download_url' => 'http://localhost/deal1/invoice/download/1/a33fa0898753b5eb0ee4f90a6514a77e',
                'view_url' => 'http://localhost/deal1/invoice/view/1/a33fa0898753b5eb0ee4f90a6514a77e',
                'api_download' => 'http://localhost/deal1/shopkart-api/order/1/invoice/download',
            ],
        ],
    ],
    [
        'id' => 'order-invoice-download',
        'group' => 'orders',
        'name' => 'Download Order Invoice PDF',
        'method' => 'GET',
        'path' => 'order/1/invoice/download',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Streams the tax invoice as application/pdf for the order owner. Replace :id. In the explorer, response may look like binary text — in Postman/app save as file. Prefer Order Invoice Links first to get a signed public URL if you need a shareable link without JWT.',
        'query' => [],
        'headers' => ['Accept' => 'application/pdf'],
        'body' => null,
        'sample_response' => [
            'note' => 'Binary PDF body (Content-Type: application/pdf). Not JSON.',
            'Content-Disposition' => 'attachment; filename="invoice-SK903246A0.pdf"',
        ],
    ],

    /* ========== SHIPPING ========== */
    [
        'id' => 'shipping-track',
        'group' => 'shipping',
        'name' => 'Track Shipment',
        'method' => 'POST',
        'path' => 'shipping/track',
        'auth' => false,
        'verified' => true,
        'how' => 'Public. Pass tracking_number / bill_code OR order_number. Pulls JT Express when enabled.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['order_number' => 'SK-20260728-001'],
        'sample_response' => [
            'success' => false,
            'message' => 'Shipment not found.',
            'data' => [],
        ],
    ],

    /* ========== PAYMENT ========== */
    [
        'id' => 'pay-create',
        'group' => 'payment',
        'name' => 'Create Payment Order',
        'method' => 'POST',
        'path' => 'payment/create-order',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Product purchase via Curlec (FPX / e-wallet / card — NOT the shop in-app wallet). After checkout payment.next_step=create_payment_order, call this, then open Curlec with callback_url + redirect:true from this response. After bank/card return, Curlec posts to callback_url which confirms the order and shows success/fail. Also call payment/verify from the Razorpay handler when it fires.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['order_id' => 101],
        'sample_response' => [
            'success' => true,
            'message' => 'Payment order created.',
            'data' => [
                'razorpay_order_id' => 'order_xxx',
                'amount' => 23050,
                'pay_amount' => 230.50,
                'currency' => 'MYR',
                'key_id' => 'rzp_test_xxx',
                'callback_url' => 'https://2deal.my/shopkart-api/payment/razorpay-return',
                'redirect' => true,
                'prefill' => [
                    'name' => 'Siti Aminah',
                    'contact' => '+60123456789',
                    'contact_digits' => '60123456789',
                    'contact_local' => '0123456789',
                ],
            ],
        ],
    ],
    [
        'id' => 'pay-verify',
        'group' => 'payment',
        'name' => 'Verify Payment',
        'method' => 'POST',
        'path' => 'payment/verify',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. After Curlec success OR failure for product purchase. If captured: confirmed=true and cart_clear_lines — remove those product_ids from the app cart (DB is already cleared). If Touch n Go still processing (payment_pending_gateway): pending=true, HTTP 200, do not retry. If card_declined / payment_session_expired / GATEWAY_ERROR: success=false, HTTP 200, data.failed=true, data.retry_allowed=true, message is user-facing. Open My Orders Complete payment to retry. Never treat pending as a hard fail.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'order_id' => 101,
            'razorpay_order_id' => 'order_xxx',
            'razorpay_payment_id' => 'pay_xxx',
            'razorpay_signature' => 'sig_xxx',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Payment successful! Your order is confirmed.',
            'data' => [
                'confirmed' => true,
                'order_id' => 101,
                'order_number' => 'SK-20260728-001',
                'payment_status' => 'paid',
                'status' => 'confirmed',
                'cart_clear_lines' => [
                    ['product_id' => 12, 'variant_id' => 3],
                ],
                'order' => ['id' => 101, 'payment_status' => 'paid', 'status' => 'confirmed'],
            ],
        ],
    ],
    [
        'id' => 'pay-order-status',
        'group' => 'payment',
        'name' => 'Order Payment Status',
        'method' => 'GET',
        'path' => 'payment/order-status',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. After Curlec closes for product purchase. Query order_id, razorpay_order_id, razorpay_payment_id. Confirms order when Curlec e-wallet/FPX/card payment captured.',
        'query' => [
            'order_id' => '101',
            'razorpay_order_id' => 'order_xxx',
            'razorpay_payment_id' => 'pay_xxx',
        ],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Payment successful! Your order is confirmed.',
            'data' => ['confirmed' => true, 'order_id' => 101, 'payment_status' => 'paid', 'status' => 'confirmed'],
        ],
    ],
    [
        'id' => 'pay-toyyib-return',
        'group' => 'payment',
        'name' => 'ToyyibPay Return',
        'method' => 'GET',
        'path' => 'payment/toyyibpay-return',
        'auth' => false,
        'verified' => true,
        'how' => 'Browser return URL from ToyyibPay (not typically called by the mobile app directly). Query params from gateway.',
        'query' => ['status_id' => '1', 'billcode' => 'xxx', 'order_id' => ''],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Payment return processed.',
            'data' => [],
        ],
    ],
    [
        'id' => 'pay-toyyib-callback',
        'group' => 'payment',
        'name' => 'ToyyibPay Callback',
        'method' => 'POST',
        'path' => 'payment/toyyibpay-callback',
        'auth' => false,
        'verified' => true,
        'how' => 'Server-to-server callback from ToyyibPay. Mobile app does not call this; documented for completeness.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['status_id' => '1', 'billcode' => 'xxx', 'order_id' => ''],
        'sample_response' => ['success' => true, 'message' => 'OK', 'data' => []],
    ],

    /* ========== REVIEWS ========== */
    [
        'id' => 'reviews-list',
        'group' => 'reviews',
        'name' => 'Product Reviews',
        'method' => 'GET',
        'path' => 'product/31/reviews',
        'auth' => false,
        'verified' => true,
        'how' => 'Public approved reviews for a product id. Each review may include images[] and videos[] (url + file_path).',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [[
                'id' => 1,
                'rating' => 5,
                'title' => 'Great product',
                'body' => 'Excellent quality.',
                'user_name' => 'Customer',
                'created_at' => '2026-07-29 10:00:00',
                'images' => [['media_type' => 'image', 'url' => 'https://example.com/assets/uploads/reviews/a.jpg']],
                'videos' => [],
            ]],
        ],
    ],
    [
        'id' => 'reviews-elig',
        'group' => 'reviews',
        'name' => 'Review Eligibility',
        'method' => 'GET',
        'path' => 'product/31/reviews/eligibility',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Optional JWT. can_review only when logged-in purchaser who has not already reviewed (purchase_required / login_required / already_reviewed).',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'can_review' => false,
                'reason' => 'purchase_required',
                'message' => 'Only customers who purchased this product can write a review.',
            ],
        ],
    ],
    [
        'id' => 'reviews-store',
        'group' => 'reviews',
        'name' => 'Submit Review',
        'method' => 'POST',
        'path' => 'reviews',
        'auth' => true,
        'verified' => true,
        'how' => 'JWT required. Only purchasers. rating 1–5, body required. Optional multipart: images[] (max 5 jpg/png/webp) and video (max 25MB mp4/webm). Starts as pending.',
        'query' => [],
        'headers' => ['Content-Type' => 'multipart/form-data or application/json', 'Authorization' => 'Bearer <jwt>'],
        'body' => [
            'product_id' => 31,
            'rating' => 5,
            'title' => 'Great product',
            'body' => 'Excellent quality and packaging.',
            'images[]' => '(file, optional, up to 5)',
            'video' => '(file, optional)',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Review submitted. It will appear after approval.',
            'data' => ['id' => 1, 'media' => []],
        ],
    ],

    /* ========== CONTENT ========== */
    [
        'id' => 'content-testimonials',
        'group' => 'content',
        'name' => 'Testimonials',
        'method' => 'GET',
        'path' => 'testimonials',
        'auth' => false,
        'verified' => true,
        'how' => 'Public customer testimonials for home/about.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [['id' => '1', 'author_name' => 'Priya Sharma', 'quote' => 'Absolutely stunning saree!']],
        ],
    ],
    [
        'id' => 'content-blogs',
        'group' => 'content',
        'name' => 'Blog List',
        'method' => 'GET',
        'path' => 'blogs',
        'auth' => false,
        'verified' => true,
        'how' => 'Published blog posts list.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => ['success' => true, 'message' => 'Success', 'data' => []],
    ],
    [
        'id' => 'content-blog',
        'group' => 'content',
        'name' => 'Blog Detail',
        'method' => 'GET',
        'path' => 'blog/sample-slug',
        'auth' => false,
        'verified' => true,
        'how' => 'Single blog by slug. 404 if missing.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => false,
            'message' => 'Blog post not found',
            'data' => [],
        ],
    ],
    [
        'id' => 'content-settings',
        'group' => 'content',
        'name' => 'Site Settings',
        'method' => 'GET',
        'path' => 'site-settings',
        'auth' => false,
        'verified' => true,
        'how' => 'Public storefront settings: name, currency, tax, shipping thresholds.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'site_name' => '2DEAL',
                'tax_rate' => 18,
                'shipping_charge' => 50,
                'free_shipping_above' => 999,
            ],
        ],
    ],
    [
        'id' => 'content-seo-page',
        'group' => 'content',
        'name' => 'SEO Page',
        'method' => 'GET',
        'path' => 'seo/page/home',
        'auth' => false,
        'verified' => true,
        'how' => 'SEO meta for a page key (home, shop, about…). Also available as /seo?path=/',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'page_key' => 'home',
                'meta_title' => 'ShopKart - Online Saree & Ethnic Wear Store',
                'meta_description' => 'Buy authentic sarees…',
            ],
        ],
    ],
    [
        'id' => 'content-seo-global',
        'group' => 'content',
        'name' => 'SEO Global',
        'method' => 'GET',
        'path' => 'seo/global',
        'auth' => false,
        'verified' => true,
        'how' => 'Global SEO defaults (site name, default meta, OG).',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'site_name' => '2DEAL',
                'meta_title' => '2DEAL - Buy Silk, Cotton & Designer Sarees Online',
            ],
        ],
    ],

    /* ========== CONTACT ========== */
    [
        'id' => 'contact-submit',
        'group' => 'contact',
        'name' => 'Submit Contact Enquiry',
        'method' => 'POST',
        'path' => 'contact',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Mobile/web contact form. Required: name, email, message. Optional: phone, subject, source (app|web). JWT optional — prefills user details. Saved in Admin → Contacts (shopkart/contacts). Status 201.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'name' => 'API Docs Test',
            'email' => 'apidocs@example.com',
            'phone' => '0123456789',
            'subject' => 'Order help',
            'message' => 'Hello from mobile app contact form',
            'source' => 'app',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Thank you! We will get back to you shortly.',
            'data' => [
                'id' => 12,
                'status' => 'new',
                'source' => 'app',
                'subject' => 'Order help',
            ],
        ],
    ],
    [
        'id' => 'contact-list',
        'group' => 'contact',
        'name' => 'List My Contact Enquiries',
        'method' => 'GET',
        'path' => 'contact',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'With JWT: own enquiries. Without JWT: pass ?email=. Optional status, limit, page.',
        'query' => ['email' => 'apidocs@example.com', 'limit' => '20', 'page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'contacts' => [[
                    'id' => 12,
                    'name' => 'API Docs Test',
                    'email' => 'apidocs@example.com',
                    'phone' => '0123456789',
                    'subject' => 'Order help',
                    'message' => 'Hello from mobile app contact form',
                    'source' => 'app',
                    'status' => 'new',
                    'created_at' => '2026-07-30 18:00:00',
                ]],
                'total' => 1,
                'page' => 1,
                'limit' => 20,
                'total_pages' => 1,
            ],
        ],
    ],
    [
        'id' => 'contact-show',
        'group' => 'contact',
        'name' => 'Get Contact Enquiry',
        'method' => 'GET',
        'path' => 'contact/12',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Fetch one enquiry by id. Allowed if JWT owns it or ?email= matches.',
        'query' => ['email' => 'apidocs@example.com'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'id' => 12,
                'name' => 'API Docs Test',
                'email' => 'apidocs@example.com',
                'phone' => '0123456789',
                'subject' => 'Order help',
                'message' => 'Hello from mobile app contact form',
                'source' => 'app',
                'status' => 'new',
                'created_at' => '2026-07-30 18:00:00',
            ],
        ],
    ],

    /* ========== MISC ========== */
    [
        'id' => 'misc-newsletter',
        'group' => 'misc',
        'name' => 'Newsletter Subscribe',
        'method' => 'POST',
        'path' => 'newsletter',
        'auth' => false,
        'verified' => true,
        'how' => 'Subscribe email to newsletter. Idempotent if already subscribed.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['email' => 'apidocs@example.com'],
        'sample_response' => [
            'success' => true,
            'message' => 'Subscribed successfully!',
            'data' => [],
        ],
    ],

    /* ========== AFFILIATE ENQUIRY ========== */
    [
        'id' => 'affiliate-enquiry-post',
        'group' => 'affiliate',
        'name' => 'Submit Affiliate Enquiry',
        'method' => 'POST',
        'path' => 'affiliate/enquiry',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Public (JWT optional). Required: name, email, message. Optional: phone, promo_code. Stores in affiliate_enquiries + emails admin.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'name' => 'Ali Reseller',
            'email' => 'ali@example.com',
            'phone' => '0123456789',
            'promo_code' => 'ALI10',
            'message' => 'I want to join the affiliate programme.',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Thank you! Your affiliate enquiry has been submitted.',
            'data' => ['id' => 1, 'status' => 'new'],
        ],
    ],
    [
        'id' => 'affiliate-enquiry-list',
        'group' => 'affiliate',
        'name' => 'List Affiliate Enquiries',
        'method' => 'GET',
        'path' => 'affiliate/enquiry',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'With JWT: own enquiries. Without JWT: pass ?email=. Optional status, limit, page.',
        'query' => ['email' => 'ali@example.com', 'limit' => '20', 'page' => '1'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'enquiries' => [[
                    'id' => 1,
                    'name' => 'Ali Reseller',
                    'email' => 'ali@example.com',
                    'phone' => '0123456789',
                    'promo_code' => 'ALI10',
                    'status' => 'new',
                    'created_at' => '2026-07-29 10:00:00',
                ]],
                'total' => 1,
                'page' => 1,
                'limit' => 20,
                'total_pages' => 1,
            ],
        ],
    ],
    [
        'id' => 'affiliate-enquiry-show',
        'group' => 'affiliate',
        'name' => 'Get Affiliate Enquiry',
        'method' => 'GET',
        'path' => 'affiliate/enquiry/1',
        'auth' => 'optional',
        'verified' => true,
        'how' => 'Fetch one enquiry by id. Allowed if JWT owns it or ?email= matches.',
        'query' => ['email' => 'ali@example.com'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'id' => 1,
                'name' => 'Ali Reseller',
                'email' => 'ali@example.com',
                'message' => 'I want to join the affiliate programme.',
                'status' => 'new',
                'created_at' => '2026-07-29 10:00:00',
            ],
        ],
    ],

    /* ========== AFFILIATE AUTH & PORTAL ========== */
    [
        'id' => 'affiliate-register',
        'group' => 'affiliate',
        'name' => 'Affiliate Register',
        'method' => 'POST',
        'path' => 'affiliate/register',
        'auth' => false,
        'verified' => true,
        'how' => 'Public. Required: name, email, phone, password. Optional promo_code (auto-generated if empty). Creates pending affiliate (awaits admin approval). Status 201.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'name' => 'Ali Reseller',
            'email' => 'ali.affiliate@example.com',
            'phone' => '0123456789',
            'password' => 'Test@1234',
            'promo_code' => 'ALI10',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Registered',
            'data' => [
                'affiliate' => [
                    'id' => 8,
                    'name' => 'Aff Probe User',
                    'email' => 'affprobe@example.com',
                    'phone' => '60129105152',
                    'promo_code' => 'AP105152',
                    'commission_rate' => 5,
                    'status' => 'pending',
                    'kyc_status' => 'pending',
                    'pending_commission' => 0,
                    'paid_commission' => 0,
                    'checkout_orders' => 0,
                    'total_sales' => 0,
                ],
                'promo_code' => 'AP105152',
                'message' => 'Registration submitted. Await admin approval.',
            ],
        ],
    ],
    [
        'id' => 'affiliate-login',
        'group' => 'affiliate',
        'name' => 'Affiliate Login',
        'method' => 'POST',
        'path' => 'affiliate/login',
        'auth' => false,
        'verified' => false,
        'how' => 'Public. Email + password. Returns affiliate JWT (type=affiliate). Rejects pending/rejected/suspended. Explorer auto-saves token.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'email' => 'ali.affiliate@example.com',
            'password' => 'Test@1234',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'token' => 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...',
                'affiliate' => [
                    'id' => 12,
                    'name' => 'Ali Reseller',
                    'email' => 'ali.affiliate@example.com',
                    'promo_code' => 'ALI10',
                    'status' => 'approved',
                    'pending_commission' => 120.5,
                    'paid_commission' => 80,
                ],
            ],
        ],
    ],
    [
        'id' => 'affiliate-logout',
        'group' => 'affiliate',
        'name' => 'Affiliate Logout',
        'method' => 'POST',
        'path' => 'affiliate/logout',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Blacklists current Bearer token.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => new stdClass(),
        'sample_response' => [
            'success' => true,
            'message' => 'Logged out successfully.',
            'data' => [],
        ],
    ],
    [
        'id' => 'affiliate-profile-get',
        'group' => 'affiliate',
        'name' => 'Affiliate Profile',
        'method' => 'GET',
        'path' => 'affiliate/profile',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Full profile including bank + address fields.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'affiliate' => [
                    'id' => 12,
                    'name' => 'Ali Reseller',
                    'promo_code' => 'ALI10',
                    'bank_name' => 'Maybank',
                    'city' => 'Kuala Lumpur',
                ],
            ],
        ],
    ],
    [
        'id' => 'affiliate-profile-put',
        'group' => 'affiliate',
        'name' => 'Update Affiliate Profile',
        'method' => 'PUT',
        'path' => 'affiliate/profile',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Editable: address, bank, about, phone (not email/promo).',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'city' => 'Kuala Lumpur',
            'state' => 'Wilayah Persekutuan',
            'bank_name' => 'Maybank',
            'bank_account_name' => 'Ali Reseller',
            'bank_account_number' => '1234567890',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Profile updated.',
            'data' => ['affiliate' => ['id' => 12, 'city' => 'Kuala Lumpur']],
        ],
    ],
    [
        'id' => 'affiliate-dashboard',
        'group' => 'affiliate',
        'name' => 'Affiliate Dashboard',
        'method' => 'GET',
        'path' => 'affiliate/dashboard',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Stats, promo_code, referral_url, min_payout, next Thursday payout date.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'stats' => [
                    'pending_commission' => 120.5,
                    'paid_commission' => 80,
                    'checkout_orders' => 14,
                ],
                'promo_code' => 'ALI10',
                'referral_url' => 'https://example.com/?ref=ALI10',
                'min_payout' => 50,
                'next_payout' => '2026-07-30',
            ],
        ],
    ],
    [
        'id' => 'affiliate-commissions',
        'group' => 'affiliate',
        'name' => 'Affiliate Commissions',
        'method' => 'GET',
        'path' => 'affiliate/commissions',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Query page & limit (max 50). Order-linked commission rows.',
        'query' => ['page' => '1', 'limit' => '20'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'commissions' => [[
                    'id' => 1,
                    'order_id' => 101,
                    'order_amount' => 250,
                    'commission_amount' => 12.5,
                    'status' => 'pending',
                ]],
                'total' => 1,
                'page' => 1,
            ],
        ],
    ],
    [
        'id' => 'affiliate-ledger',
        'group' => 'affiliate',
        'name' => 'Affiliate Ledger',
        'method' => 'GET',
        'path' => 'affiliate/ledger',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Earn/payout ledger rows. Query page & limit.',
        'query' => ['page' => '1', 'limit' => '20'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'ledger' => [[
                    'id' => 1,
                    'type' => 'earn',
                    'amount' => 12.5,
                    'balance_after' => 120.5,
                ]],
                'total' => 1,
                'page' => 1,
                'limit' => 20,
            ],
        ],
    ],
    [
        'id' => 'affiliate-payouts',
        'group' => 'affiliate',
        'name' => 'Affiliate Payouts',
        'method' => 'GET',
        'path' => 'affiliate/payouts',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. List payout requests for this affiliate.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'payouts' => [[
                    'id' => 3,
                    'amount' => 100,
                    'status' => 'pending',
                    'created_at' => '2026-07-28 10:00:00',
                ]],
                'total' => 1,
            ],
        ],
    ],
    [
        'id' => 'affiliate-payout-request',
        'group' => 'affiliate',
        'name' => 'Request Affiliate Payout',
        'method' => 'POST',
        'path' => 'affiliate/payouts/request',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Requests payout of pending commission (must meet min_payout). Settled next Thursday.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => new stdClass(),
        'sample_response' => [
            'success' => true,
            'message' => 'Payout request submitted for next Thursday.',
            'data' => ['payout_id' => 5],
        ],
    ],
    [
        'id' => 'affiliate-check-promo',
        'group' => 'affiliate',
        'name' => 'Check Affiliate Promo Availability',
        'method' => 'GET',
        'path' => 'affiliate/check-promo',
        'auth' => false,
        'verified' => true,
        'how' => 'Public. Query ?code=ALI10 — returns available true/false for registration promo uniqueness.',
        'query' => ['code' => 'ALI10'],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => ['available' => false],
        ],
    ],
    [
        'id' => 'affiliate-banks',
        'group' => 'affiliate',
        'name' => 'List Banks',
        'method' => 'GET',
        'path' => 'affiliate/banks',
        'auth' => false,
        'verified' => false,
        'how' => 'Public. Active Malaysian banks for affiliate profile / payout dropdown.',
        'query' => [],
        'headers' => [],
        'body' => null,
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'banks' => [
                    ['id' => 1, 'name' => 'Maybank', 'code' => 'MBB'],
                    ['id' => 2, 'name' => 'CIMB Bank', 'code' => 'CIMB'],
                ],
            ],
        ],
    ],
    [
        'id' => 'affiliate-track',
        'group' => 'affiliate',
        'name' => 'Track Affiliate Ref (Deprecated)',
        'method' => 'POST',
        'path' => 'affiliate/track',
        'auth' => false,
        'verified' => false,
        'how' => 'Deprecated stub. Real tracking is checkout promo_code / ?ref=. Validates approved promo and returns affiliate_id.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['promo_code' => 'ALI10'],
        'sample_response' => [
            'success' => true,
            'message' => 'Success',
            'data' => [
                'affiliate_id' => 12,
                'promo_code' => 'ALI10',
                'message' => 'Affiliate tracking uses checkout promo codes. Share your promo or ?ref= link.',
            ],
        ],
    ],
    [
        'id' => 'affiliate-forgot-password',
        'group' => 'affiliate',
        'name' => 'Affiliate Forgot Password',
        'method' => 'POST',
        'path' => 'affiliate/forgot-password',
        'auth' => false,
        'verified' => true,
        'how' => 'Public. Sends password reset link email for affiliate account.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => ['email' => 'ali.affiliate@example.com'],
        'sample_response' => [
            'success' => true,
            'message' => 'Password reset link sent to your email.',
            'data' => [],
        ],
    ],
    [
        'id' => 'affiliate-forgot-verify',
        'group' => 'affiliate',
        'name' => 'Affiliate Verify Reset Code',
        'method' => 'POST',
        'path' => 'affiliate/forgot-password/verify',
        'auth' => false,
        'verified' => false,
        'how' => 'Public. Email + 6-digit code → reset_token for reset-password step.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'email' => 'ali.affiliate@example.com',
            'code' => '123456',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Verified. Set your new password.',
            'data' => ['reset_token' => 'abc...'],
        ],
    ],
    [
        'id' => 'affiliate-reset-password',
        'group' => 'affiliate',
        'name' => 'Affiliate Reset Password',
        'method' => 'POST',
        'path' => 'affiliate/reset-password',
        'auth' => false,
        'verified' => false,
        'how' => 'Public. email + reset_token + password + password_confirmation (min 6 chars).',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'email' => 'ali.affiliate@example.com',
            'reset_token' => 'abc...',
            'password' => 'NewPass@123',
            'password_confirmation' => 'NewPass@123',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Password updated. You can sign in.',
            'data' => [],
        ],
    ],
    [
        'id' => 'affiliate-change-password-request',
        'group' => 'affiliate',
        'name' => 'Request Change-Password Code',
        'method' => 'POST',
        'path' => 'affiliate/change-password/request',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. Emails 6-digit code to change password while logged in.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => new stdClass(),
        'sample_response' => [
            'success' => true,
            'message' => 'Verification code sent to ali.affiliate@example.com',
            'data' => [],
        ],
    ],
    [
        'id' => 'affiliate-change-password',
        'group' => 'affiliate',
        'name' => 'Change Affiliate Password',
        'method' => 'POST',
        'path' => 'affiliate/change-password',
        'auth' => true,
        'verified' => false,
        'how' => 'Affiliate JWT required. code (6 digits) + password + password_confirmation.',
        'query' => [],
        'headers' => ['Content-Type' => 'application/json'],
        'body' => [
            'code' => '123456',
            'password' => 'NewPass@123',
            'password_confirmation' => 'NewPass@123',
        ],
        'sample_response' => [
            'success' => true,
            'message' => 'Password changed successfully.',
            'data' => [],
        ],
    ],
];
